### ISSUE TITLE
CHORE - Update method to override masthead colour

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#26]
The masthead colour override setting outputs this CSS:

```css
.vf-wp-theme .embl-group-page--vf-header--bg-color {
 background: #000;
}
```

The method the VF expects has now changed and needs to be updated to output:  

```css
.vf-masthead {
    --vf-masthead__color--background: #00;
}
```
