### ISSUE TITLE
Fix tag archive styles (taxonomy term)

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-wp#261]
Blocking #251 

here’s a fun one

WordPress loves to dump a load of random class names in `<body>` for example:

```
archive tag tag-tag-one tag-366 logged-in admin-bar wp-embed-responsive ebi-vf1-integration vf-wp-theme vf-body vf-global-theme--primary vf-global-layout--normal customize-support
```

Specifically `tag` when viewing a taxonomy term archive.

and wouldn’t you know `ebi-global.css` also has a `tag` style.

Which results in:

<img width="1110" alt="Screenshot 2020-04-30 at 11 18 21" src="https://user-images.githubusercontent.com/998922/80699769-12b47800-8acc-11ea-9594-0b70dff34dc6.png">

I suppose the easiest solution is to "depollute" the body classes.  However, I don't like filtering out WordPress defaults because its possible some plugin relies on this convention and `tag` class.

Maybe more CSS to reset at a low specificity?

```css
.tag {
  display: inline-block;
  padding: 0.33333rem 0.5rem;
  font-size: 0.8rem;
  line-height: 1;
  white-space: nowrap;
  background: #007c82;
  color: white;
  border-bottom: none;
}
```
