### ISSUE TITLE
Optimize taxonomy sync process

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-wp#520]
We have option to sync EMBL taxonomy from ContentHub to Wordpress, whenever we click the link to sync we are getting timeout in sync process.
![Screenshot 2020-10-05 at 10 48 35](https://user-images.githubusercontent.com/1227241/95070401-f6aea580-06ff-11eb-8ab3-9e17777c5a7f.png)

@khawkins98 Spillios We need to remove any unwanted taxonomies as the list is growing so I think it takes time to process and sync them in Wordpress.

**Comment by sandykadam** [comment]
`

Hi!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, EMBL Taxonomy.

First, visit your website (https://wwwdev.embl.org/about/info/imaging-centre/) and check for any visible issues. Next, visit the page where the error was caught (https://wwwdev.embl.org/about/info/imaging-centre/about/info/imaging-centre/wp-admin/edit-tags.php?taxonomy=embl_taxonomy&sync=true) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://wwwdev.embl.org/about/info/imaging-centre/wp-login.php?action=enter_recovery_mode&rm_token=RRrADZHedrAK13jg43D9Kc&rm_key=vyKaPgmQ3LXMg62EbWlFxP

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.5.3
Current theme: VF-WP Groups (version 1.0.0-beta.5)
Current plugin: EMBL Taxonomy (version 1.0.0-beta.1)
PHP version 7.3.14



Error Details
=============
An error of type E_ERROR was caused in line 404 of the file /var/www/drupal/embl.org.about.info/_imaging-centre/dist/wp-content/plugins/embl-taxonomy/includes/register.php. Error message: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 135168 bytes)


`

**Comment by dbushell** [comment]
The raw taxonomy JSON from the Content Hub is around 100kb so that should be parsable in one go.

With 235 terms and multiple database updates per-term that might be an issue — but looking at the error, it's failing before it even gets to that stage.

The error is in `generate_terms` which maps EMBL terms to the WordPress taxonomy structure. It's a recursive function which might point to the memory error. Or there might be a circular references in the EMBL terms.

I'll investigate further tomorrow and see if I can identify what is causing the error and if I can fix it.

Ideally the plugin needs someone more proficient in PHP to rewrite it. I wrote this plugin as a proof-of-concept two years ago. It was only meant to be a working placeholder to illustrate how the WP taxonomy structure should be set up.

**Comment by dbushell** [comment]
I've identifed some issues with the API data containing invalid parent term IDs like:

```php
string(4) "none"
string(19) "string/EBI Training"
````

I'm filtering them out with [a regexp pattern](https://api.drupal.org/api/drupal/core!lib!Drupal!Component!Uuid!Uuid.php/constant/Uuid%3A%3AVALID_PATTERN/):
```php
const UUID_PATTERN = '#^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$#';
```

But that doesn't actually solve this memory bug so I'll keep going...

**Comment by dbushell** [comment]
Bug is in this part with the nested loop:

```php
      foreach ($term['parents'] as $parent_id) {
        foreach ($api_terms as $new_parent) {
```
[embl-taxonomy/includes/register.php](https://github.com/visual-framework/vf-wp/blob/v1.0.0-beta.27/wp-content/plugins/embl-taxonomy/includes/register.php#L411)

That is hugely inefficient 🔥 I will optimise that and see where it gets me.

**Comment by dbushell** [comment]
@khawkins98 something I've noticed.

The API data has similar terms with `display_name` of "Seminars":

```yaml
{
  "33f3a158-1ca6-4d20-a75c-23f39dce6c34": {
    "name": "EMBL Events term",
    "uuid": "33f3a158-1ca6-4d20-a75c-23f39dce6c34",
    "nid": "26735",
    "name_display": "Seminars",
    "primary": "what",
    "parents": ["302cfdf7-365b-462a-be65-82c7b783ebf7"],
    "type": "term"
  },
  "4057de86-552d-438e-9782-1a18cec5eeb3": {
    "name": "EMBL Seminars term",
    "uuid": "4057de86-552d-438e-9782-1a18cec5eeb3",
    "nid": "26737",
    "name_display": "Seminars",
    "primary": "what",
    "parents": ["33f3a158-1ca6-4d20-a75c-23f39dce6c34"],
    "type": "term"
  }
}
```

"EMBL Seminars term" is a child of "EMBL Events term".

All seminars are grandchildren resulting in these WordPress terms:

![Screenshot 2020-11-26 at 09 58 57](https://user-images.githubusercontent.com/998922/100337493-5b370400-2fcf-11eb-9e79-0068c193c5ca.png)

Where the display name hierarchy becomes "Seminars > Seminars" 🤔
