### ISSUE TITLE
Editor UX: Disable the WP default youtube block

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-wp#693]
A recurring confusion I've noticed for users is that they use the WP default "video" or "YouTube" blocks to embed videos and not the VF-specific embed. 

Complicating matters:

- it's hard to know how to make the vf embed URL
- the WP default blocks work, but they're not responsive

Example: https://wwwdev.embl.org/editorhub/2021/01/27/responsive-video-test/

![image](https://user-images.githubusercontent.com/928100/105975575-653cb800-608f-11eb-916f-48d4cd3fa53c.png)

![image](https://user-images.githubusercontent.com/928100/105975616-7259a700-608f-11eb-87a5-6d2d2c418b8c.png)

Suggestions:

1. Add some in-context documentation to the vf embed on how to generate the URL
2. Disable (or warn) on using the default YouTube and video responsive
3. Or: make the default blocks responsive

**Comment by khawkins98** [comment]
@kasprzyk-sz if we add some CSS like this, it will at least make the videos responsive even if the user makes the wrong choice:

```css

.wp-embed-aspect-16-9 {
  position: relative;
  padding-bottom: 56.25%;
  height: 0;
}

.wp-embed-aspect-16-9 iframe {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```

That CSS should live as an npm installable `vf-wp-extensions`, so that editorHub and new embeded content will work outside of WP sites. 

I can pick that part up.
